services:
  tekus.api:
    image: tekus.api
    build:
      context: .
      dockerfile: src/Tekus.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=tekus;User Id=sa;Password=password;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=password
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: